# Generated by Django 4.0.5 on 2022-07-11 06:18

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('gallery_photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo4', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('gallery_photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo4', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('gallery_photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_photo4', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
