# Generated by Django 4.0.5 on 2022-07-07 05:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
