# Generated by Django 4.0.5 on 2022-07-08 08:51

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('gallery', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('services', tinymce.models.HTMLField(blank=True, null=True)),
                ('created', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
