# Generated by Django 4.0.5 on 2022-07-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidiary',
            old_name='gallery',
            new_name='gallery1',
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='gallery2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='gallery3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='gallery4',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='gallery5',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
