# Generated by Django 4.0.5 on 2022-07-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0002_rename_gallery_subsidiary_gallery1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='gallery4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='gallery5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
