# Generated by Django 4.0.5 on 2022-10-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0003_alter_subsidiary_gallery1_alter_subsidiary_gallery2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberName1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberName2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberName3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberName4',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberPhoto1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberPhoto2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberPhoto3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='teamMemberPhoto4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
